name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and NPM
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Build and package app
      run: npm run build

    - name: Check commit message
      run: |
        if [[ $(git log -1 --pretty=%B) == update ]]; then
          echo "new move"
        else
          echo "no update"
        fi
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /var/www/react-app/my-app
          git pull origin master
          npm run build
          
